### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by ZYJoey123** [hevalazizoglu/automated-theorem-prover#1]
Hi, I am learning AI but not very familiar with Python, I'm not quite understand the input part, could you please give an example of the input if there is constant or function? For example, the clause is B(a) or B(f(x)). Thanks.

**Comment by hevalazizoglu** [comment]
Hi @ZYJoey123 
Here is a sample input and output:
```
Input:
1
3 1
p(A, f(t))
q(z), ∼ p(z, f(B)) 
∼ q(y), r(y)
∼ r(A)

Output:
yes
∼ r(A)$ ∼ q(y), r(y)$ ∼ q(A)
∼ q(A)$q(z), ∼ p(z, f(B))$ ∼ p(A, f(B)) 
∼ p(A, f (B))$p(A, f (t))$empty clause

```

> The first line of the input file contains an integer stating the number of tasks to be solved. Then for the following lines, two positive integers n and m corresponding to the number of clauses in the base set B and the number of clauses in the set G of clauses obtained from the negation of the theorem, respectively. In each of the following n/m lines (line 2 to line n + 1/line n + 2 to line n + m + 1 with respect to the line containing n and m for that task), there is a single clause from B/G which contains literals (atomic predicate or its negation) separated by commas.

> The first line of the output file contains ”yes”, or ”no” corresponding to derivable or not derivable. Note that empty-clause symbolizes empty clause. The same pattern goes on for the rest of the tasks. In each of the following lines, there are 3 clauses separated by ”$” where the first two are parent clauses, the third is the resolvent.

Hope this helps.

**Comment by ZYJoey123** [comment]
Thanks a lot.

Happy Thanks Giving.

**Comment by Khaledjallouli** [comment]
Hi @hevalazizoglu,

have you the code in python of these input and output please ? 
Thank you very much :)

**Comment by hevalazizoglu** [comment]
@Khaledjallouli sorry, I really couldn't get your request.
If you're asking for the code to solve this problem it is in the code section. Or if you're asking the code for read/write it is in source as well.

**Comment by Khaledjallouli** [comment]
@hevalazizoglu I couldn't run the program, Can you help me to solve this problem please ? 
 
file = open("input.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'input.txt'

and may be for the output file it will be the same problem, what should I do pleaase

**Comment by hevalazizoglu** [comment]
@Khaledjallouli You need to have a input.txt on the directory you have this project. Please create it with the content of input I shared above.

**Comment by Khaledjallouli** [comment]
you mean input.txt should contain this code 
tasks = []
    num_tasks = int(file.readline().strip("\n"))

    while num_tasks > 0:
        num_list = file.readline().strip("\n").split()
        num_base_clauses = int(num_list[0])
        num_obtained_clauses = int(num_list[1])
        clause_list = []
        while num_base_clauses > 0:
            base_clause = file.readline().strip("\n").replace("\t", "").replace(" ", "")
            num_base_clauses -= 1
            clause_content = create_clause_list([], base_clause, False)
            clause = Clause(clause_content, [])
            clause_list.append(clause)
        while num_obtained_clauses > 0:
            obtained_clause = file.readline().strip("\n").replace("\t", "").replace(" ", "")
            num_obtained_clauses -= 1
            clause_content = create_clause_list([], obtained_clause, False)
            clause = Clause(clause_content, [])
            clause_list.append(clause)
        num_tasks -= 1
        task = Task(clause_list)
        tasks.append(task)

**Comment by hevalazizoglu** [comment]
@Khaledjallouli no, that is the code itself. I mean this:
```
1
3 1
p(A, f(t))
q(z), ∼ p(z, f(B)) 
∼ q(y), r(y)
∼ r(A)
```

**Comment by Khaledjallouli** [comment]
@hevalazizoglu  Have you an idea about how can I solve this problem pleaase ? 
I am so sorry for my questions, I am beginner 


Traceback (most recent call last):

line 354, in <module>
    clause_content = create_clause_list([], base_clause, False)
 line 314, in create_clause_list
    return create_clause_list(so_far + [tomatoes], rest, is_negative)
line 329, in create_clause_list
    return create_clause_list(so_far, from_now_on[1:], is_negative)
  line 333, in create_clause_list
    return so_far + create_clause_list([], from_now_on[1:], is_negative)

TypeError: can only concatenate list (not "NoneType") to list
